server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

base64:
  img:
    type: data:image/jpeg;base64,

spring:
  application:
    name: minormargin
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/minormargin?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    userName: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      readOnly: false
      connectionTimeout: 3000000
      idleTimeout: 600000
      maximumPoolSize: 15
      pool-name: pool-lxl
      connectionTestQuery: SELECT 1
      minimum-idle: 10
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 500
        max-idle: 1000
        min-idle: 4
        max-wait: 6000ms