server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: minormargin
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/minormargin?useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=true
    userName: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      readOnly: false
      connectionTimeout: 3000000
      idleTimeout: 600000
      maximumPoolSize: 15
      pool-name: pool-lxl
      connectionTestQuery: SELECT 1
      minimum-idle: 10
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 500
        max-idle: 1000
        min-idle: 4
        max-wait: 6000ms